services:
  web:
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - DEBUG=true

  celery-worker:
    command: uv run celery -A app.worker.celery_app worker --loglevel=debug
    volumes:
      - .:/app

  celery-beat:
    command: uv run celery -A app.worker.celery_app beat --loglevel=debug
    volumes:
      - .:/app

  wa-bridge:
    volumes:
      - ./wa_bridge:/app
      - /app/node_modules
